DEVICE_PATH := device/samsung/a01core

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a53

TARGET_BOOTLOADER_BOARD_NAME := a01core
TARGET_NO_RADIOIMAGE := true

TARGET_BOARD_PLATFORM := mt6739

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048

BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216

BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
